#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///

# ─── How to run ───
#   uv run docs/sejong/scripts/test_delegation_wave_validation.py
# ──────────────────────────

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from dataclasses import replace
from pathlib import Path

from delegation_run import check_failures
from delegation_run_model import Backend, Budget, DelegationContractError, DelegationRun, Worker, WorkerId, save_run
from delegation_wave import (
    ReceiptId,
    TerminalReceiptRequest,
    TerminalStatus,
    WaveId,
    add_wave,
    fan_in,
    open_wave,
    record_terminal,
)


SCRIPT_PATH = Path(__file__).resolve()
REPO_ROOT = SCRIPT_PATH.parents[3]
SEUNGJEONGWON = SCRIPT_PATH.with_name("seungjeongwon_run.py")


def closed_run(status: TerminalStatus = TerminalStatus.COMPLETED) -> DelegationRun:
    run = DelegationRun(
        run_id="correlation-run",
        created_at="2026-07-11T00:00:00Z",
        budget=Budget(1, 1, 1, 1),
        workers=(Worker(WorkerId("worker-a"), Backend.NATIVE, 0),),
    )
    run = add_wave(run, WaveId("wave-1"), (WorkerId("worker-a"),), ())
    run = open_wave(run, WaveId("wave-1"))
    run = record_terminal(
        run,
        TerminalReceiptRequest(
            receipt_id=ReceiptId("receipt-worker-a"),
            wave_id=WaveId("wave-1"),
            worker_id=WorkerId("worker-a"),
            backend_worker_ref="native://worker-a",
            worker_contract_ref="contract://worker-a",
            worker_output_ref="output://worker-a",
            terminal_status=status,
            summary="worker-a terminal",
            evidence_refs=("evidence://worker-a",),
            blocker=None if status is TerminalStatus.COMPLETED else f"{status.value} disposition",
        ),
    )
    return fan_in(run, WaveId("wave-1"))[0]


def payload_for(run: DelegationRun, path: Path) -> dict:
    save_run(path, run)
    return json.loads(path.read_text(encoding="utf-8"))


def write_payload(path: Path, payload: dict) -> tuple[str, ...]:
    path.write_text(json.dumps(payload), encoding="utf-8")
    return check_failures(path)


def run_seungjeongwon(arguments: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SEUNGJEONGWON), *arguments],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
    )


class DelegationWaveCorrelationTests(unittest.TestCase):
    def test_generated_terminal_aggregates_are_valid(self) -> None:
        # Given/When/Then: every aggregate generated by Core passes persisted validation.
        for status in (TerminalStatus.COMPLETED, TerminalStatus.FAILED, TerminalStatus.BLOCKED):
            with self.subTest(status=status), tempfile.TemporaryDirectory() as tmp:
                path = Path(tmp) / "delegation-run.json"
                save_run(path, closed_run(status))
                self.assertEqual(check_failures(path), ())

    def test_passed_fan_in_without_terminal_receipts_is_rejected(self) -> None:
        # Given: a passed fan-in whose terminal evidence was deleted.
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "delegation-run.json"
            payload = payload_for(closed_run(), path)
            payload["receipts"] = [receipt for receipt in payload["receipts"] if receipt["receipt_type"] == "fan_in"]

            # When/Then: the persisted run is not accepted on fan-in claims alone.
            self.assertTrue(write_payload(path, payload))

    def test_terminal_identity_and_state_tampering_is_rejected(self) -> None:
        cases = {
            "receipt_id": ("receipt_id", "forged-receipt"),
            "worker_id": ("worker_id", "unknown-worker"),
            "terminal_status": ("terminal_status", "failed"),
            "run_id": ("run_id", "other-run"),
            "backend": ("backend", "team_executor"),
        }
        for name, (field, value) in cases.items():
            with self.subTest(name=name), tempfile.TemporaryDirectory() as tmp:
                path = Path(tmp) / "delegation-run.json"
                payload = payload_for(closed_run(), path)
                terminal = next(item for item in payload["receipts"] if item["receipt_type"] == "worker_terminal")
                terminal[field] = value
                self.assertTrue(write_payload(path, payload))

    def test_fan_in_coverage_and_recomputed_fields_are_enforced(self) -> None:
        cases = {
            "required_workers": ("required_worker_ids", ["worker-a", "worker-extra"]),
            "terminal_ids": ("terminal_receipt_ids", ["receipt-worker-a", "receipt-worker-a"]),
            "aggregate": ("aggregate_status", "blocked"),
            "blocking_ids": ("blocking_receipt_ids", ["receipt-worker-a"]),
            "run_id": ("run_id", "other-run"),
        }
        for name, (field, value) in cases.items():
            with self.subTest(name=name), tempfile.TemporaryDirectory() as tmp:
                path = Path(tmp) / "delegation-run.json"
                payload = payload_for(closed_run(), path)
                fan_in_receipt = next(item for item in payload["receipts"] if item["receipt_type"] == "fan_in")
                fan_in_receipt[field] = value
                self.assertTrue(write_payload(path, payload))

    def test_orphan_receipts_and_open_wave_fan_in_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "delegation-run.json"
            payload = payload_for(closed_run(), path)
            orphan = dict(next(item for item in payload["receipts"] if item["receipt_type"] == "worker_terminal"))
            orphan.update(receipt_id="orphan-receipt", wave_id="unknown-wave")
            payload["receipts"].append(orphan)
            self.assertTrue(write_payload(path, payload))

        for status in ("pending", "active"):
            with self.subTest(status=status), tempfile.TemporaryDirectory() as tmp:
                path = Path(tmp) / "delegation-run.json"
                payload = payload_for(closed_run(), path)
                payload["waves"][0]["status"] = status
                self.assertTrue(write_payload(path, payload))

    def test_receipt_boundary_and_required_references_are_enforced(self) -> None:
        cases = {
            "format": ("format", "wrong-format"),
            "authority": ("authority", "final_authority"),
            "backend_worker_ref": ("backend_worker_ref", ""),
            "worker_contract_ref": ("worker_contract_ref", ""),
            "worker_output_ref": ("worker_output_ref", ""),
            "evidence_refs": ("evidence_refs", []),
        }
        for name, (field, value) in cases.items():
            with self.subTest(name=name), tempfile.TemporaryDirectory() as tmp:
                path = Path(tmp) / "delegation-run.json"
                payload = payload_for(closed_run(), path)
                terminal = next(item for item in payload["receipts"] if item["receipt_type"] == "worker_terminal")
                terminal[field] = value
                self.assertTrue(write_payload(path, payload))

    def test_seungjeongwon_rejects_detached_and_later_tampered_runs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            delegation_path = root / "delegation-run.json"
            fan_in_path = root / "fan-in.json"
            seungjeongwon_path = root / "seungjeongwon-run.json"
            run = closed_run()
            save_run(delegation_path, run)
            fan_in_receipt = next(item for item in run.receipts if item["receipt_type"] == "fan_in")
            fan_in_path.write_text(json.dumps(fan_in_receipt), encoding="utf-8")
            started = run_seungjeongwon(
                [
                    "start", "--path", str(seungjeongwon_path), "--run-id", "seung-correlation",
                    "--goal", "Reject tampered delegation evidence.",
                    "--success-criterion", "Only correlated fan-in is accepted.",
                    "--verification-method", "Run persisted validation.",
                ]
            )
            self.assertEqual(started.returncode, 0, started.stderr)

            payload = payload_for(run, delegation_path)
            payload["receipts"] = [item for item in payload["receipts"] if item["receipt_type"] == "fan_in"]
            delegation_path.write_text(json.dumps(payload), encoding="utf-8")
            detached = run_seungjeongwon(
                [
                    "add-fan-in", "--path", str(seungjeongwon_path),
                    "--delegation-run", str(delegation_path), "--receipt", str(fan_in_path),
                ]
            )
            self.assertNotEqual(detached.returncode, 0)
            self.assertIn("invalid delegation run ref", detached.stderr)

            save_run(delegation_path, run)
            attached = run_seungjeongwon(
                [
                    "add-fan-in", "--path", str(seungjeongwon_path),
                    "--delegation-run", str(delegation_path), "--receipt", str(fan_in_path),
                ]
            )
            self.assertEqual(attached.returncode, 0, attached.stderr)
            payload = payload_for(run, delegation_path)
            payload["receipts"][0]["run_id"] = "tampered-run"
            delegation_path.write_text(json.dumps(payload), encoding="utf-8")
            embedded = run_seungjeongwon(["check", "--path", str(seungjeongwon_path)])
            self.assertNotEqual(embedded.returncode, 0)
            self.assertIn("invalid delegation run ref", embedded.stderr)

    def test_tampered_passed_dependency_cannot_open_downstream_wave(self) -> None:
        run = closed_run()
        extra_worker = Worker(WorkerId("worker-b"), Backend.NATIVE, 0)
        run = replace(
            run,
            budget=Budget(2, 1, 1, 2),
            workers=(*run.workers, extra_worker),
        )
        run = add_wave(
            run,
            WaveId("wave-2"),
            (WorkerId("worker-b"),),
            (WaveId("wave-1"),),
        )
        tampered = replace(
            run,
            receipts=tuple(
                receipt for receipt in run.receipts
                if receipt.get("receipt_type") != "worker_terminal"
            ),
        )

        with self.assertRaisesRegex(DelegationContractError, "invalid persisted wave state"):
            open_wave(tampered, WaveId("wave-2"))


if __name__ == "__main__":
    unittest.main()
